### ISSUE TITLE
Conflict with the module ZfTable | Deactivate dynamically the locale strategy

### ISSUE THREAD

**Issue by yannickvid** [juriansluiman/SlmLocale#68]
When using SlmLocale with the strategy "uripath", the module ZfTable (https://github.com/dudapiotr/ZfTable) is not working anymore. (Issue: https://github.com/dudapiotr/ZfTable/issues/57)

I believe that the issue is due to the fact that the strategy add the locale in the URL and the Ajax requests of the module ZfTable do not know how to handle it. 

Is there a way to deactivate dynamically the strategy in a controller to avoid the addition of the locale in the URL?

Has anyone tried to work with both these modules at the same time?

**Comment by yannickvid** [comment]
This may not be the best way to do it, but at least it solves the issue:

For the calls in Zftable views, instead of calling:
$("#tableContainer").zfTable('/admin/members/ajax-list');

You need to call the full URL with the locale:
$("#tableContainer").zfTable('<?php echo "http://" . $_SERVER['SERVER_NAME']; ?>/en/admin/members/ajax-list');

**Comment by juriansluiman** [comment]
Why are you using static links? If you use the zf2 view helper, SlmLocale is configured to inject the base path including the language part.

**Comment by yannickvid** [comment]
Hello,

Thank you for your answer, using View Helpers is actually better yes.

For people facing the same problem, a better way to solve the issue is to call:

$("#tableContainer").zfTable('<?php echo $this->url('admin-members', array('action' => 'ajax-list'), array('force_canonical' => true))?>');

Please note that you need the "array('force_canonical' => true)" to display the full URL, otherwise it will not work.
